### ISSUE TITLE
Alafile out - overwrites target file

### ISSUE THREAD

**Issue by hamild** [AlaSQL/node-red-contrib-alasql#12]
I'm not sure if this is a problem due to my lack of understanding of json and that stuff but here goes anyway. 
I send an inventory of machines and their postcodes to a node called Postcode Lookup with the result that it returns the geographical coordinates of the machine from its postcode. This works fine and I now want to save the resulting list of positions ...  
If I use the "file" node with the action "append to file" selected, I get a file with the machine listing showing id, latitude and longitude. 
However, if I try to use Alafile out node (which is excellent btw!) , let's say to create a csv or an Excel file, I just get one record saved to the csv or xls file (I _think_ it's the last machine in the list)  which suggests that the node is overwriting rather than appending to the new file ... which is what I want.   Have I missed something or is there an issue with my input to Alafile? 

thanks!

**Comment by mathiasrw** [comment]
AlaSQL can not add to a file - only replace it

**Comment by hamild** [comment]
So ... somehow I need to collect my records into a single "unit" before invoking Alafile? 
Or maybe I should used AlaSQL and write an SQL procedure to save all the records to the spreadsheet?
I tried saving to MongoDB ... which works but I am having trauma getting the data back out to merge with operational data for each machine.  The idea is that eventually, we would put the operational data on a map...     I guess I could simply get the geo coordinates for each operational record but that seems a little wasteful - I thought it would be better to have a reference source (Inventory) with the positional data..

**Comment by mathiasrw** [comment]
What you can do is to read the file and merge the results and rewrite to the file

OR

Add data to a table in mem (a normal alasql table) and export to file every time you update it. Technically you risk to lose data if node is turned off at the wrong time.
