### ISSUE TITLE
Array parameters passed via msg.payload to alasql node not working

### ISSUE THREAD

**Issue by tmdoit** [AlaSQL/node-red-contrib-alasql#16]
Array of parameters passed in msg.payload is treated by alasql in insert as one parameter, ie.:
`
[{"id":"c1a70029.98ea7","type":"alasql","z":"2d89d4b5.a581bc","name":"","query":"CREATE TABLE ArticleGroups (Code string, Name string);","x":250,"y":1120,"wires":[["67e913ab.e7446c"]]},{"id":"af2252b0.09bc6","type":"inject","z":"2d89d4b5.a581bc","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":100,"y":1120,"wires":[["c1a70029.98ea7"]]},{"id":"67e913ab.e7446c","type":"function","z":"2d89d4b5.a581bc","name":"","func":"msg.payload = [\"fd\",\"df\"];\nreturn msg;","outputs":1,"noerr":0,"x":400,"y":1120,"wires":[["23c7e6be.9f2bea"]]},{"id":"23c7e6be.9f2bea","type":"alasql","z":"2d89d4b5.a581bc","name":"","query":"INSERT INTO ArticleGroups VALUES (?,?);\nSELECT * FROM ArticleGroups;","x":550,"y":1120,"wires":[["d4e3b5c3.4e4e28","d43d6056.198fb"]]},{"id":"d4e3b5c3.4e4e28","type":"alasql","z":"2d89d4b5.a581bc","name":"","query":"DROP TABLE ArticleGroups;","x":710,"y":1120,"wires":[[]]},{"id":"d43d6056.198fb","type":"debug","z":"2d89d4b5.a581bc","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":700,"y":1060,"wires":[]}]
`

**Comment by tmdoit** [comment]
I found the problem which is already fixed: https://github.com/AlaSQL/node-red-contrib-alasql/commit/2e7aff67ffd2b466b44b70ca203f8598216fb00e.
Please update node-red package.

**Comment by mathiasrw** [comment]
Its not updated? crazy, Will look into this today.
