### ISSUE TITLE
msg.payload contains a object (alarms) and each alarm is a array element

### ISSUE THREAD

**Issue by erlanger24** [AlaSQL/node-red-contrib-alasql#20]
My msg.payload contains a object (alarms) and each alarm is a array element.

My question now is:
how would the SQL query look like in order to count all alarmSource = "operation"

![Capture](https://user-images.githubusercontent.com/53535487/62311435-1d35d880-b48c-11e9-816a-8657d13c63f2.PNG)

**Comment by mathiasrw** [comment]
`SELECT count(*) from ? where alarmSource = 'operation'`

**Comment by erlanger24** [comment]
Result counts 0 : 
array[1]
0: object
COUNT(*): 0

-> how can i tell the query to search within the elements of alarms ?

**Comment by mathiasrw** [comment]
What is the input and what do you hope to get as output
