### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by tmdoit** [AlaSQL/node-red-contrib-alasql#26]
Before please undo commit https://github.com/AlaSQL/node-red-contrib-alasql/commit/4e9ac45bb5b32e11aefb88eae47e983dc1a05a1a

**Comment by mathiasrw** [comment]
How come you dont like 4e9ac45?

**Comment by tmdoit** [comment]
Because now we can set payload for AlaSQL via two msg properties: msg.topic and msg.query. I don't see reason why duplicating solution for the same use case: pass payload to AlaSQL. I'm not opting which name for the property is better, just msg.topic was mentioned first and we should keep that way.

**Comment by Steve-Mcl** [comment]
the version of this node on NPM cannot set the query at all from a message.

This is a screen shot of `node-red.contrib-alasql.js` on github today...
![image](https://user-images.githubusercontent.com/44235289/85745291-7f7b7580-b6fd-11ea-82cb-0467bcd918ec.png)


this is a screen shot of `node-red.contrib-alasql.js` downloaded from NPM today...
![image](https://user-images.githubusercontent.com/44235289/85745254-77bbd100-b6fd-11ea-8a55-2fb9cd74bf9e.png)



Both NPM and GITHUB package.json are labelled as v2.0.0

Something isnt right!

As for using msg.topic or msg.query - PLEASE LEAVE THIS IN - 2 reasons...
1. backwards compatibility
2. familiarity (some DB nodes use `topic`, others use `query`) - its doing no harm left as is

**Comment by mathiasrw** [comment]
@Steve-Mcl Thank you for chipping in your point regarding topic or query. We will leave them - and close this task. 

I will look into what is going on with the npm package. I fear that a build did not make it and we pushed with correct source but without an updated build.

**Comment by mathiasrw** [comment]
Mystery solved - I had accidentally pushed from the wrong branch. Aw. Super bad. Thank you for letting us know. 

Version 2.0.1 is out now.

**Comment by Steve-Mcl** [comment]
thanks for the swift action @mathiasrw
