### ISSUE TITLE
Could you execute "npm publish" as v2.0.0 ?

### ISSUE THREAD

**Issue by 1ft-seabass** [AlaSQL/node-red-contrib-alasql#29]
Hi! I'm appreciate your great node.

I would like to use updated `v2.0.0` because I'm interested at `this.topic` or `this.query` active parameters function. I think that it is nice idea!

I installed at https://flows.nodered.org/node/node-red-contrib-alasql using Node-RED GUI pallete. But It was `v1.1.0` in 2020/5/14.

Could you update to `v2.0.0` as npm version if you can? I'm looking forward to upgraded `v2.0.0` and that function.

**Comment by mathiasrw** [comment]
Done!

**Comment by 1ft-seabass** [comment]
Great Thanks! And I noticed that I couldn't tell you about the newest way of updating node. Now isn't automatically node update.

like this.
https://discourse.nodered.org/t/how-to-add-update-nodes-to-the-flow-library/25294

So,

![image](https://user-images.githubusercontent.com/2148840/82523726-002bdc80-9b68-11ea-878a-789170bbf35c.png)

I went to your node page.

![image](https://user-images.githubusercontent.com/2148840/82523735-05892700-9b68-11ea-9124-3226793d4b8b.png)

![image](https://user-images.githubusercontent.com/2148840/82523741-091cae00-9b68-11ea-9fef-cf65f2453ca1.png)

I clicked `request refresh` on your node page after logined own GitHub account!

![image](https://user-images.githubusercontent.com/2148840/82523754-0d48cb80-9b68-11ea-9d7c-dbb8df09fd3d.png)

Your node refreshed immediately! And Node-RED Nodes twitter account catched your node update!

https://twitter.com/red_nodes/status/1263320627181760512

Thanks.
