### ISSUE TITLE
How to add AlaSQL to Node-RED market?

### ISSUE THREAD

**Issue by agershun** [AlaSQL/node-red-contrib-alasql#4]
http://flows.nodered.org/

**Comment by mathiasrw** [comment]
AlaSQL was part of the node-red market as it had the `node-red` keyword

Based on this issue: https://github.com/AlaSQL/node-red-contrib-alasql/issues/1 I removed the keyword (https://github.com/AlaSQL/node-red-contrib-alasql/commit/6f3cde7f6c49f38d4b81479f30aa59c773f9a2a8) as it was breaking the node-red of people who installed it. 

I reinserted the keyword again when I published your changes: https://github.com/AlaSQL/node-red-contrib-alasql/commit/473ab14d4f46edef4b918d1fd137d190b689be32

So - I think it will pop into the results when they have scanned github again...

**Comment by mathiasrw** [comment]
Ohh - and I have to publish to npm too... sorry for that. 

I have upgraded to version 1.0.0 for people to know its not beta
