### ISSUE TITLE
Outputs from Query Node 

### ISSUE THREAD

**Issue by arobinsongit** [AlaSQL/node-red-contrib-alasql#5]
Is there a specific reason the query node has no outputs?  It seems odd since you put the results of the query into the msg.payload.  Maybe I am not quite understanding the intent of this node.  We are looking to use the node inside a larger flow that is essentially performing ETL type functions.

**Comment by agershun** [comment]
Thank you for reporting of the problem! I fixed it here in develop branch.

https://github.com/AlaSQL/node-red-contrib-alasql/blob/develop/node-red-contrib-alasql.html

**Comment by agershun** [comment]
Updated. @arobinsongit May I ask you to test the new version?

**Comment by PrasadSunil** [comment]
Today i used it. It is working as expected when we use $0 but not sure why it is not giving result if we use it on array and user $1.
