### ISSUE TITLE
Issue in query on Array using $1 and so on

### ISSUE THREAD

**Issue by PrasadSunil** [AlaSQL/node-red-contrib-alasql#6]
Query is working fine as expected on msg.payload if we use $0, but in case of array if we use $1 gives error.

**Comment by agershun** [comment]
Could you share some code (or picture with the diagram) how you are going to use the node? Now it designed to use only one argument ($0).  I will browse the examples of nodes with variable number of inputs...

**Comment by PrasadSunil** [comment]
sorry, i was referring to the document where it is written "Refer to input data in msg.payload with $0 in your SQL. If msg.payload is an array the first value will be $0, the second $1 and so forth." can we do something like passing multiple JSON to the node (if not multiple, then may me merging multiple JSON to one before passing) and then applying query on it. for example i have 2 tables/json gender and employee and i want to run join query on these tables inside the alasql node and return output.

**Comment by mathiasrw** [comment]
Is it correct that you want to do a

```sql
SELECT * from $0 person JOIN $1 gender ON person.gender = gender.id
```
and your msg.payload is equal to something like 

```
[
[{name:'alice', gender: 1}, {name:'bob', gender: 2}],
[{id:1, name: 'Lady'}, {id:2, name: 'Guy'}],
]
```

?

**Comment by PrasadSunil** [comment]
yes, i want to do something like this.

**Comment by PrasadSunil** [comment]
just now i checked, with same sample it gives error  "TypeError: Cannot read property 'length' of undefined"
i have created a function node with below code.
----function node----------------------------------------------------
msg.payload=[
[{name:'alice', gender: 1}, {name:'bob', gender: 2}],
[{id:1, name: 'Lady'}, {id:2, name: 'Guy'}],
]
return msg;

----alasql node--------------------------------------------------
SELECT * from $0 person JOIN $1 gender ON person.gender = gender.id;

**Comment by mathiasrw** [comment]
Terrible...

Can you see what line the error is from?
